/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ssc.Agent.Api
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ChatRequest,
  ChatResponse,
  HTTPValidationError,
  ProblemDetails
} from '../model';

import { customFetch } from '../../api-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type sendChatMessageResponse200 = {
  data: ChatResponse
  status: 200
}

export type sendChatMessageResponse400 = {
  data: ProblemDetails
  status: 400
}

export type sendChatMessageResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type sendChatMessageResponseSuccess = (sendChatMessageResponse200) & {
  headers: Headers;
};
export type sendChatMessageResponseError = (sendChatMessageResponse400 | sendChatMessageResponse422) & {
  headers: Headers;
};

export type sendChatMessageResponse = (sendChatMessageResponseSuccess | sendChatMessageResponseError)

export const getSendChatMessageUrl = () => {




  return `/api/chat`
}

/**
 * @summary Sendchatmessage
 */
export const sendChatMessage = async (chatRequest: ChatRequest, options?: Parameters<typeof customFetch>[1]): Promise<sendChatMessageResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<sendChatMessageResponse>(getSendChatMessageUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(chatRequest)
  }
);}





export const getSendChatMessageMutationKey = () => ['sendChatMessage'] as const;

export const getSendChatMessageMutationOptions = <TError = ProblemDetails | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendChatMessage>>, TError,SendChatMessageMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof sendChatMessage>>, TError,SendChatMessageMutationVariables, TContext> => {

const mutationKey = getSendChatMessageMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendChatMessage>>, SendChatMessageMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  sendChatMessage(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SendChatMessageMutationResult = NonNullable<Awaited<ReturnType<typeof sendChatMessage>>>
    export type SendChatMessageMutationBody = ChatRequest
    export type SendChatMessageMutationError = ProblemDetails | HTTPValidationError
    export type SendChatMessageMutationVariables = {data: ChatRequest}

    /**
 * @summary Sendchatmessage
 */
export const useSendChatMessage = <TError = ProblemDetails | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendChatMessage>>, TError,SendChatMessageMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendChatMessage>>,
        TError,
        SendChatMessageMutationVariables,
        TContext
      > => {
      return useMutation(getSendChatMessageMutationOptions(options), queryClient);
    }
