/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ssc.Agent.Api
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  TestAgentResponse
} from '../model';

import { customFetch } from '../../api-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type runTestAgentResponse200 = {
  data: TestAgentResponse
  status: 200
}

export type runTestAgentResponseSuccess = (runTestAgentResponse200) & {
  headers: Headers;
};
;

export type runTestAgentResponse = (runTestAgentResponseSuccess)

export const getRunTestAgentUrl = () => {




  return `/api/test-agent`
}

/**
 * @summary Runtestagent
 */
export const runTestAgent = async ( options?: Parameters<typeof customFetch>[1]): Promise<runTestAgentResponse> => {

  return customFetch<runTestAgentResponse>(getRunTestAgentUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getRunTestAgentMutationKey = () => ['runTestAgent'] as const;

export const getRunTestAgentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runTestAgent>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof runTestAgent>>, TError,void, TContext> => {

const mutationKey = getRunTestAgentMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof runTestAgent>>, void> = () => {


          return  runTestAgent(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RunTestAgentMutationResult = NonNullable<Awaited<ReturnType<typeof runTestAgent>>>

    export type RunTestAgentMutationError = unknown


    /**
 * @summary Runtestagent
 */
export const useRunTestAgent = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runTestAgent>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof runTestAgent>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getRunTestAgentMutationOptions(options), queryClient);
    }
