/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ssc.Agent.Api
 * OpenAPI spec version: 1.0.0
 */
import type { ValidationError } from './validationError';

export interface HTTPValidationError {
  detail?: ValidationError[];
}
