/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ssc.Agent.Api
 * OpenAPI spec version: 1.0.0
 */

export interface TestAgentResponse {
  status: string;
  message: string;
  agentResponse: string;
}
