/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Ssc.Agent.Api
 * OpenAPI spec version: 1.0.0
 */
import type { ValidationErrorCtx } from './validationErrorCtx';

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}
