import * as Dialog from '@radix-ui/react-dialog'
import {
  AssistantRuntimeProvider,
  ComposerPrimitive,
  MessagePrimitive,
  ThreadPrimitive,
} from '@assistant-ui/react'
import { useAgUiRuntime } from '@assistant-ui/react-ag-ui'
import { HttpAgent } from '@ag-ui/client'
import { useQuery } from '@tanstack/react-query'
import type { ReactNode } from 'react'
import { useMemo, useState } from 'react'
import {
  Activity,
  ArrowUp,
  Check,
  ChevronDown,
  Menu,
  PanelLeft,
  Plus,
  Settings2,
  ShieldCheck,
  X,
} from 'lucide-react'
import { getHealth } from './api/system/system'
import { authenticatedFetch } from './api-mutator'
import { AuthControls } from './features/auth'
import { create } from 'zustand'
import './App.css'

type WorkspaceState = {
  activeMode: 'chat' | 'activity'
  setActiveMode: (activeMode: WorkspaceState['activeMode']) => void
}

const useWorkspaceStore = create<WorkspaceState>((set) => ({
  activeMode: 'chat',
  setActiveMode: (activeMode) => set({ activeMode }),
}))

const AGENTS = {
  'ssc-agent': {
    label: 'Chat agent',
    endpoint: '/api/ag-ui/ssc-agent',
  },
  coding: {
    label: 'Coding agent',
    endpoint: '/api/ag-ui/coding',
  },
} as const

type AgentId = keyof typeof AGENTS

function UserMessage() {
  return (
    <MessagePrimitive.Root className="message message-user">
      <div className="message-label">You</div>
      <MessagePrimitive.Parts />
    </MessagePrimitive.Root>
  )
}

function AssistantMessage({ label }: { label: string }) {
  return (
    <MessagePrimitive.Root className="message message-assistant">
      <div className="message-label"><span className="agent-dot" /> {label}</div>
      <MessagePrimitive.If hasContent={false}>
        <ThreadPrimitive.If running>
          <div className="skeleton-lines" aria-hidden="true">
            <span className="skeleton-line skeleton-line-wide" />
            <span className="skeleton-line skeleton-line-medium" />
            <span className="skeleton-line skeleton-line-short" />
          </div>
        </ThreadPrimitive.If>
      </MessagePrimitive.If>
      <MessagePrimitive.Parts />
    </MessagePrimitive.Root>
  )
}

function AgentActivity({ agentLabel }: { agentLabel: string }) {
  return (
    <ThreadPrimitive.If running>
      <div className="agent-activity" role="status" aria-live="polite">
        <span className="activity-spinner" aria-hidden="true">
          <span className="spinner-orbit" />
          <span className="spinner-core" />
        </span>
        <span className="activity-copy">
          <span className="activity-title">{agentLabel} is working</span>
          <span className="activity-detail">Thinking, streaming, or running a tool…</span>
        </span>
        <span className="activity-pulse" aria-hidden="true" />
      </div>
    </ThreadPrimitive.If>
  )
}

function AgentThread({ agentLabel }: { agentLabel: string }) {
  const AgentAssistantMessage = () => <AssistantMessage label={agentLabel} />

  return (
    <ThreadPrimitive.Root className="thread">
      <ThreadPrimitive.Viewport className="thread-viewport">
        <ThreadPrimitive.Empty>
          <div className="thread-empty">
            <div className="empty-symbol"><Activity size={22} /></div>
            <p className="empty-kicker">Ready when you are</p>
            <h2>Start a conversation with your agent.</h2>
            <p>Ask for analysis, implementation help, or a second pair of eyes on your next decision.</p>
            <ThreadPrimitive.Suggestion
              className="test-message-button"
              prompt="Say hello and confirm that the SSC Agent is connected."
              send
            >
              Send one test message
            </ThreadPrimitive.Suggestion>
          </div>
        </ThreadPrimitive.Empty>
        <ThreadPrimitive.Messages
          components={{ UserMessage, AssistantMessage: AgentAssistantMessage }}
        />
        <AgentActivity agentLabel={agentLabel} />
        <ThreadPrimitive.ViewportFooter>
          <div className="composer-wrap">
            <ComposerPrimitive.Root className="composer">
              <ComposerPrimitive.Input
                className="composer-input"
                placeholder="Ask the agent anything..."
                aria-label="Message the agent"
                autoFocus
              />
              <ComposerPrimitive.Send className="send-button" aria-label="Send message">
                <ArrowUp size={18} strokeWidth={2.5} />
              </ComposerPrimitive.Send>
            </ComposerPrimitive.Root>
            <p className="composer-note">Responses are generated by <strong>gpt-5.3-codex</strong> via Microsoft Foundry.</p>
          </div>
        </ThreadPrimitive.ViewportFooter>
      </ThreadPrimitive.Viewport>
    </ThreadPrimitive.Root>
  )
}

function AgentRuntime({ agentId, children }: { agentId: AgentId; children: ReactNode }) {
  const agent = AGENTS[agentId]
  const agUiAgent = useMemo(
    () => new HttpAgent({
      url: `${import.meta.env.VITE_API_BASE_URL ?? ''}${agent.endpoint}`,
      fetch: authenticatedFetch,
    }),
    [agent.endpoint],
  )
  const runtime = useAgUiRuntime({ agent: agUiAgent })

  return <AssistantRuntimeProvider runtime={runtime}>{children}</AssistantRuntimeProvider>
}

function PreferencesDialog() {
  return (
    <Dialog.Root>
      <Dialog.Trigger asChild>
        <button className="icon-text-button" type="button">
          <Settings2 size={17} /> Preferences
        </button>
      </Dialog.Trigger>
      <Dialog.Portal>
        <Dialog.Overlay className="dialog-overlay" />
        <Dialog.Content className="dialog-content">
          <div className="dialog-heading">
            <div>
              <Dialog.Title>Workspace preferences</Dialog.Title>
              <Dialog.Description>Connection settings for this local workspace.</Dialog.Description>
            </div>
            <Dialog.Close asChild>
              <button className="icon-button" type="button" aria-label="Close preferences">
                <X size={18} />
              </button>
            </Dialog.Close>
          </div>
          <div className="preference-row">
            <div><span className="preference-label">Provider</span><span className="preference-value">Microsoft Foundry</span></div>
            <ShieldCheck size={18} />
          </div>
          <div className="preference-row">
            <div><span className="preference-label">Model deployment</span><span className="preference-value">gpt-5.3-codex</span></div>
            <Check size={18} />
          </div>
          <Dialog.Close asChild>
            <button className="dialog-close-button" type="button">Done</button>
          </Dialog.Close>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  )
}

function App() {
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [agentId, setAgentId] = useState<AgentId>('ssc-agent')
  const activeMode = useWorkspaceStore((state) => state.activeMode)
  const setActiveMode = useWorkspaceStore((state) => state.setActiveMode)
  const healthQuery = useQuery({
    queryKey: ['/health'],
    queryFn: ({ signal }) => getHealth({ signal }),
    refetchInterval: 30_000,
  })
  const apiStatus = healthQuery.data?.status === 200 ? 'online' : healthQuery.isPending ? 'checking' : 'offline'
  const selectedAgent = AGENTS[agentId]

  return (
    <AgentRuntime key={agentId} agentId={agentId}>
      <div className="app-shell">
        <header className="topbar">
          <div className="brand-lockup">
            <button className="mobile-menu icon-button" type="button" aria-label="Open navigation" onClick={() => setSidebarOpen((open) => !open)}>
              <Menu size={20} />
            </button>
            <div className="brand-mark">S</div>
            <div><span className="brand-name">SSC / AGENT</span><span className="brand-subtitle">Engineering workspace</span></div>
          </div>
          <div className="topbar-actions">
            <div className="system-status"><span className={`status-pip ${apiStatus}`} /> API {apiStatus}</div>
            <PreferencesDialog />
            <AuthControls />
          </div>
        </header>
        <div className="workspace">
          <aside className={`sidebar ${sidebarOpen ? 'sidebar-open' : ''}`}>
            <div className="sidebar-header"><span>Workspace</span><button className="icon-button" type="button" aria-label="Collapse navigation" onClick={() => setSidebarOpen(false)}><PanelLeft size={17} /></button></div>
            <button className="new-thread" type="button" onClick={() => window.location.reload()}><Plus size={17} /> New conversation</button>
            <nav className="nav-list" aria-label="Workspace navigation">
              <button className={`nav-item ${activeMode === 'chat' ? 'active' : ''}`} type="button" onClick={() => setActiveMode('chat')}><span className="nav-icon"><Activity size={17} /></span> Conversations</button>
              <button className={`nav-item ${activeMode === 'activity' ? 'active' : ''}`} type="button" onClick={() => setActiveMode('activity')}><span className="nav-icon"><ChevronDown size={17} /></span> Activity log <span className="nav-count">0</span></button>
            </nav>
            <div className="sidebar-footer"><span className="footer-line" /><span>Local development</span><span className="version-label">v0.1</span></div>
          </aside>
          {sidebarOpen && <button className="sidebar-scrim" type="button" aria-label="Close navigation" onClick={() => setSidebarOpen(false)} />}
          <main className="main-panel">
            <div className="panel-heading">
              <div><span className="section-kicker">{activeMode === 'chat' ? 'Conversation 01' : 'System activity'}</span><h1>{activeMode === 'chat' ? 'Agent console' : 'Activity log'}</h1></div>
              <label className="model-chip agent-selector">
                <span className="model-chip-dot" />
                <span className="agent-selector-caption">Agent</span>
                <select
                  aria-label="Select agent"
                  value={agentId}
                  onChange={(event) => setAgentId(event.target.value as AgentId)}
                >
                  {Object.entries(AGENTS).map(([id, option]) => (
                    <option key={id} value={id}>{option.label}</option>
                  ))}
                </select>
                <ChevronDown size={14} />
              </label>
            </div>
            {activeMode === 'chat' ? <AgentThread agentLabel={selectedAgent.label} /> : <div className="activity-empty"><Activity size={20} /><p>No events recorded in this session.</p></div>}
          </main>
        </div>
      </div>
    </AgentRuntime>
  )
}

export default App
